[default]
HTTPS = false
DOWNLOAD = '/storage'
MINIO_HOST = 'localhost'
MINIO_USER = 'admin' 
MINIO_PASSWORD = 'passadmin'
BUCKET = 'ows'

DB_USER = 'user'
DB_PASSWORD = '123456'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_DATABASE = 'gdb'